language: node_js
node_js:
    - stable
deploy:
    - provider: npm
      skip-cleanup: true
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      on:
          tags: true
          repo: rmarganti/re-position

    - provider: pages
      skip-cleanup: true
      github-token: $GH_TOKEN
      keep-history: true
      on:
          tags: true
          repo: rmarganti/re-position
